lenfestlab/monorepo

LICENSE, ios/App/AppDelegate.swift, ios/Cartfile, ios/project-carthage.yml, ios/project.yml
=> add license (MIT)

api/app/controllers/places_controller.rb, api/config/application.rb
=> compress API responses

ios/App/PermissionsViewController.xib
=> update onboarding copy for location permission

ios/App/AnalyticsManager.swift, ios/App/LocationManager.swift, ios/App/MotionManager.swift, ios/App/MotionViewController.swift
=> fix motion permissions analytics bug

api/.env.dev.example, api/Gemfile, api/Gemfile.lock, api/lib/tasks/notify.rake, ios/App/AppDelegate.swift, ios/App/IntroViewController.swift, ios/App/LocationManager.swift, ios/App/NotificationManager.swift
=> trigger location logging w/ silent notification

api/.env.dev.example, api/Gemfile, api/Gemfile.lock, api/app/models/post.rb, api/config/initializers/bitly.rb, api/db/migrate/20181219161543_add_short_urls.rb, api/db/schema.rb
=> API: add Post#url_short

ios/App/LocationManager.swift
=> fix: cached latest location/coordinate

ios/App/MapViewController.swift
=> Fix: Swiping bug by using UIPanGestureRecognizer

design/.gitattributes, design/here.sketch
=> add design dir, sketch file in lfs

food/api/README.md, food/api/app/models/place.rb
=> emit Place name, address

food/api/app/controllers/places_controller.rb, food/api/config/application.rb, food/api/config/environments/development.rb
=> disable ambiguous params filtering

food/api/app/controllers/categories_controller.rb, food/api/app/controllers/installations_controller.rb, food/api/app/models/installation.rb, food/api/config/routes.rb, food/api/db/migrate/20190219164029_create_installations.rb, food/api/db/schema.rb
fyi @achainan, live on stag:
```
PATCH /installations/<icloud-id>
```
=> api: add PATCH /installations

food/api/app/models/post.rb, food/api/db/migrate/20190227223749_add_posts_url.rb, food/api/db/schema.rb, food/ios/App/Info.plist
@achainan PTAL.
Live on stag, see new `post.url` field: 
https://food-stag.lenfestlab.org/places.json?lat=39.9526&limit=1000&lng=-75.1652
=> [food][api] add Post#url

food/api/app/models/category.rb, food/api/app/models/post.rb
@achainan already live on stag, swaps all 'www2' instances in URLs w/ conventional 'www'
=> [food][api] workaround philly.com "www2" bugs

food/api/app/models/category.rb
@achainan fix for category ids cache bug
=> [food][api] update cached category ids on save

food/api/app/controllers/places_controller.rb, food/api/app/models/category.rb, food/api/app/models/place.rb, food/api/app/models/post.rb, food/api/db/migrate/20190312145125_add_places_filter_cache.rb, food/api/db/schema.rb
@achainan "sort" param live on stag, supported values are: 
- "rating"
- "latest"
- "distance" (the default; omit param to sort by distance only)
https://food-stag.lenfestlab.org/places.json?lat=39.9526&limit=1000&lng=-75.1652&sort=rating
=> [food][api] sort places by rating, latest

food/api/app/controllers/places_controller.rb, food/api/app/models/place.rb, food/api/config/routes.rb, food/api/db/migrate/20190314211305_cache_place_reviewers.rb, food/api/db/schema.rb
Filter places by review author.
Live on stag, along with `GET /authors.json`
https://food-stag.lenfestlab.org/places.json?lat=39.950266&limit=1000&lng=-75.16653299999996&authors%5B%5D=576710ee-bd7d-4ecb-86c7-c4413166583a
https://food-stag.lenfestlab.org/authors.json
=> [food][api] filter places by review author

food/api/app/models/nabe.rb, food/api/app/models/place.rb, food/api/db/migrate/20190315174132_add_place_nabe_cache.rb, food/api/db/schema.rb
Adds `nabes` field to `GET /places`
Live on stag:
https://food-stag.lenfestlab.org/places.json?lat=39.9526&limit=1000&lng=-75.1652
=> [food][api] include places' nabes

food/api/app/controllers/places_controller.rb, food/api/app/models/place.rb, food/api/app/models/post.rb, food/api/db/migrate/20190318205751_unconstrain_post_source_key.rb, food/api/db/migrate/20190319155654_posts_have_many_places.rb, food/api/db/schema.rb, food/api/lib/tasks/burbs.rake, food/api/lib/tasks/nabes.rake
- places habtm posts
- fix author filtering bug
=> [food][api] support suburban data

food/api/app/models/post.rb
@achainan 	Live on stag, see "details" field:
https://food-stag.lenfestlab.org/places.json?lat=39.9526&limit=1000&lng=-75.1652
=> [food][api] emit post details as distinct fields

food/api/app/controllers/application_controller.rb, food/api/app/controllers/bookmarks_controller.rb, food/api/app/controllers/places_controller.rb, food/api/app/models/bookmark.rb, food/api/app/models/place.rb, food/api/app/models/post.rb, food/api/db/migrate/20190325203728_bookmark_places.rb, food/api/db/schema.rb
Revises all bookmarking endpoints to use Place instead of Post.
Adds `&bookmarked=1` param to `GET /places` that filters results to only those places bookmarked by the authenticated user.
@achainan
=> Api bookmarks places

food/api/app/controllers/nabes_controller.rb, food/api/app/controllers/places_controller.rb, food/api/app/models/place.rb, food/api/app/models/post.rb, food/api/db/migrate/20190326153648_post_rating_default.rb, food/api/db/migrate/20190326164026_place_address_elements.rb, food/api/db/migrate/20190326185434_cache_post_price.rb, food/api/db/migrate/20190327130945_post_photos.rb, food/api/db/schema.rb, food/api/lib/tasks/burbs.rake, food/api/lib/tasks/guide.rake, food/api/lib/tasks/reimport.rake
@achainan Already live on stag.	
Fixes the following misc. API issues.
- update: data import tasks
- fix: price filtering
- fix: GET /places bookmarks filter
- add: photo caption and credit
- fix: GET /nabes perf
- fix: omit nabes without posts
- fix: filter by rating using cache
- fix: ensure place.post is latest
=> [food][api] misc fixes

food/api/app/models/post.rb, food/ios/App/Place/Place+AttributedString.swift, food/ios/App/Place/Place.swift
@achainan already live on stag.
Resolves conflicting `price` key, adds `remainder` key.
=> [food][api] fix details price, remainder keys

food/api/Gemfile, food/api/Gemfile.lock, food/api/README.md, food/api/app/models/bookmark.rb, food/api/app/models/category.rb, food/api/app/models/place.rb, food/api/app/models/post.rb, food/api/app/models/user.rb, food/api/app/views/rails_admin/main/_post_images_data.html.slim, food/api/config/initializers/rails_admin.rb, food/api/db/migrate/20190331231404_post_rating_zero_fix.rb, food/api/db/schema.rb, food/api/lib/tasks/burbs.rake, food/api/lib/tasks/guide.rake, food/api/lib/tasks/reimport.rake
Live on stag.
@achainan One notable change: for `post.rating` we'll use `-1` to mean "unrated"; it's now the default value for that column, reserving `0` for true "zero bells" ratings. (In queries postgres evidently ranks `nil` > Int, which breaks sorting).
=> [food][api] misc admin UX improvements

food/api/.brewfile, food/api/Procfile, food/api/app/models/category.rb, food/api/app/models/nabe.rb, food/api/app/models/post.rb, food/api/config/initializers/rails_admin.rb, food/api/db/migrate/20190403142301_remove_category_constraints.rb, food/api/db/schema.rb
@achainan minor `/admin` tweaks, will self-merge.
- Post url -> "review url"
- Category: enable create, edit images; drop key constraint
- setup pgweb
=> [food][api] misc admin UX edits

food/api/app/models/post.rb, food/api/config/initializers/rails_admin.rb
- re-enable word wrap in MD fields
- admin: expose updated_at for sorting
- markdown help: reference and web editor
=> [food][api] admin tweaks

food/api/app/controllers/categories_controller.rb, food/api/app/models/category.rb, food/api/app/models/place.rb, food/api/db/migrate/20190411124900_category_windows.rb, food/api/db/schema.rb, food/api/lib/tasks/cache.rake
@achainan Live on prod, self-merging.
=> [food][api] support windowed category display

food/api/Gemfile, food/api/Gemfile.lock, food/api/app/controllers/nabes_controller.rb, food/api/app/controllers/places_controller.rb, food/api/app/models/author.rb, food/api/app/models/category.rb, food/api/app/models/image.rb, food/api/app/models/place.rb, food/api/app/models/post.rb, food/api/app/serializers/place_serializer.rb, food/api/db/migrate/20190411162355_post_windows.rb, food/api/db/schema.rb, food/api/lib/tasks/cache.rake
fyi @achainan also caches post, already live on prod
=> [food][api] windowed post display; cache posts

food/api/app/models/category.rb, food/api/app/models/image.rb, food/ios/App/Models/Category.swift, food/ios/App/Place/Place.swift, food/ios/App/Places/PlaceStore.swift, food/ios/App/Services/Cache.swift
- fix: reservations button opens wrong URL
- fix: crash searching places by name
- admin: add cuisines/guides lists
- admin: hide "cached image" field
- ios: sort guides by display_starts
- api/admin: require Category#display_starts
=> [food][ios] sort Guides by display date

food/api/README.md, food/ios/App/FilterModule.swift, food/ios/App/Models/Neighborhood.swift, food/ios/App/Notification/NotificationViewController.xib, food/ios/App/Popups/Author/AuthorViewController.swift, food/ios/App/Popups/Neighborhood/NeighborhoodViewController.swift
- fix onboarding typo
- fix authors/nabes filter views
=> [food][ios] misc bug fixes

food/ios/App/Detail/DetailViewController.swift, food/ios/App/Extensions/UIViewController+HUD.swift, food/ios/App/NotificationManager.swift, food/ios/App/Places/HomeViewController.swift, food/ios/App/Places/Map/MapViewController.swift, food/ios/App/Places/PlaceStore.swift, food/ios/App/Places/PlacesViewController.swift, food/ios/App/Services/Cache.swift, food/ios/App/Services/Context.swift
- workaround map freeze by hiding user pin during transition
- home vc: ignore cache after initial load
- notifications read action: show place if URL missing
=> [food][ios] show HUD while loading notification place

food/ios/App/ABPointAnnotation.swift, food/ios/App/Analytics/AnalyticsManager.swift, food/ios/App/AppDelegate.swift, food/ios/App/Detail/DetailViewController.swift, food/ios/App/Guides/GuidesViewController.swift, food/ios/App/LocationManager.swift, food/ios/App/Permissions/PermissionsViewController.swift, food/ios/App/Place/Place.swift, food/ios/App/Places/GuideViewController.swift, food/ios/App/Places/HomeViewController.swift, food/ios/App/Places/Map/MapViewController.swift, food/ios/App/Places/PlaceCell/PlaceCell.swift, food/ios/App/Places/PlaceStore.swift, food/ios/App/Places/PlacesViewController.swift, food/ios/App/Popups/Filter/FilterViewController.swift, food/ios/App/Services/Api.swift, food/ios/App/Services/Cache.swift
- set distance format at place to "0 miles away"
- add placemark meta to GA cds
=> [food][ios] display 5 nearest places by default

food/ios/App/AppDelegate.swift, food/ios/App/LocationManager.swift, food/ios/App/NotificationManager.swift, food/ios/App/Place/Place.swift, food/ios/App/Places/FavoritesViewController.swift, food/ios/App/Places/PlaceStore.swift, food/ios/App/Services/Cache.swift
- dedupe nearby notifications
- eager-load bookmarks to combat delayed render
=> [food][ios] sort cached places by distance on load

food/ios/App/AppDelegate.swift, food/ios/App/GuideGroup/GuideGroupCell.swift, food/ios/App/Places/HomeViewController.swift
- bind guide carousels to realm queries
- fix premature spinner dismissal on cache reset
=> [food][ios] schema update fixes

food/ios/App/GuideGroup/GuideGroupCell+UICollectionView.swift, food/ios/App/GuideGroup/GuideGroupCell.swift, food/ios/App/GuideGroup/GuideGroupViewController.swift, food/ios/project.yml
- instrument top 25 carousel swipes
- bump app version
- sort places in top 25 carousel by distance
=> [food][ios] restore "See all" button on Top 25

nabeletter/web/.env.dev.example, nabeletter/web/app/javascript/components/admin/editions/shared/EditionBodyInput/Editor/index.ts, nabeletter/web/app/javascript/components/admin/editions/shared/EditionBodyInput/index.ts, nabeletter/web/app/javascript/components/admin/index.ts
- sync progress indicator
- disable logging in prod
- reduce sync debounce to half-second
=> [nabeletter] fix: config migration bug

nabeletter/web/app/controllers/articles_controller.rb, nabeletter/web/app/javascript/components/admin/editions/shared/EditionBodyInput/sections/images/Input.ts
- more article-import logging
- clear history URL/caption upon addition
=> [nabeletter] fix: misc bugs

nabeletter/web/app/javascript/components/admin/editions/show/EditionPreviewField/index.ts, nabeletter/web/app/javascript/components/admin/editions/show/index.ts, nabeletter/web/app/resources/edition_resource.rb, nabeletter/web/app/services/delivery_service.rb, nabeletter/web/db/migrate/20200728154152_add_newsletter_from_name.rb, nabeletter/web/db/schema.rb
- restore show view preview
- disable editing once delivered
=> [nabeletter] sender name/address

nabeletter/web/app/javascript/analytics/index.ts, nabeletter/web/app/javascript/components/admin/editions/shared/EditionBodyInput/sections/footer/node.ts, nabeletter/web/app/javascript/components/admin/editions/shared/EditionBodyInput/sections/header/node.ts, nabeletter/web/app/javascript/components/admin/editions/shared/EditionBodyInput/sections/weather/node.ts, nabeletter/web/app/models/edition.rb, nabeletter/web/app/resources/edition_resource.rb, nabeletter/web/app/resources/newsletter_resource.rb, nabeletter/web/db/migrate/20200801223620_add_newsletter_lat_lng.rb, nabeletter/web/db/schema.rb
- better logo image
- restore GA's pixel for open tracking
=> [nabeletter] improve dark sky link

nabeletter/web/app/controllers/analytics_controller.rb, nabeletter/web/app/javascript/components/admin/editions/shared/EditionBodyInput/sections/events/node.ts, nabeletter/web/app/javascript/components/admin/editions/shared/EditionBodyInput/sections/footer/node.ts, nabeletter/web/app/javascript/components/admin/editions/shared/EditionBodyInput/sections/weather/node.ts, nabeletter/web/app/javascript/i18n/index.ts, nabeletter/web/app/models/edition.rb, nabeletter/web/config/initializers/rack.rb, nabeletter/web/lib/tasks/leads.rake
- footer link updates
- pixel move
- hotfix analytics MIA event name
- coerce outlook ios auto-link color
=> [nabeletter] misc bug fixes

nabeletter/web/app/controllers/analytics_controller.rb, nabeletter/web/app/javascript/components/admin/editions/shared/EditionBodyInput/sections/MarkdownField.ts, nabeletter/web/app/services/analytics_service.rb
- cd8 == uid
- cd7 (link titles) emitted by markdown
=> [nabeletter] analytics fixes

nabeletter/web/app/javascript/analytics/index.ts, nabeletter/web/app/javascript/components/admin/editions/shared/EditionBodyInput/sections/ImageList.tsx, nabeletter/web/app/javascript/components/admin/editions/shared/EditionBodyInput/sections/MarkdownField.ts, nabeletter/web/app/javascript/components/admin/editions/shared/EditionBodyInput/sections/events/Input.ts, nabeletter/web/app/javascript/components/admin/editions/shared/EditionBodyInput/sections/events/node.ts, nabeletter/web/app/javascript/components/admin/editions/shared/EditionBodyInput/sections/header/node.ts, nabeletter/web/app/javascript/components/admin/editions/shared/EditionBodyInput/sections/intro/Input.ts, nabeletter/web/app/javascript/components/admin/editions/shared/EditionBodyInput/sections/intro/node.ts, nabeletter/web/app/javascript/components/admin/editions/shared/EditionBodyInput/sections/meetings/node.ts, nabeletter/web/app/javascript/components/admin/editions/shared/EditionBodyInput/sections/news/Input.ts, nabeletter/web/app/javascript/components/admin/editions/shared/EditionBodyInput/sections/news/node.ts, nabeletter/web/app/javascript/components/admin/editions/shared/EditionBodyInput/sections/properties/Input.ts, nabeletter/web/app/javascript/components/admin/editions/shared/EditionBodyInput/sections/properties/node.ts, nabeletter/web/app/javascript/components/admin/editions/shared/EditionBodyInput/sections/section/SectionInput.ts, nabeletter/web/app/javascript/components/admin/editions/shared/EditionBodyInput/sections/section/ad/Input.ts, nabeletter/web/app/javascript/components/admin/editions/shared/EditionBodyInput/sections/section/ad/index.ts, nabeletter/web/app/javascript/components/admin/editions/shared/EditionBodyInput/sections/section/cardWrapper.ts, nabeletter/web/app/javascript/components/admin/editions/shared/EditionBodyInput/sections/section/index.ts, nabeletter/web/app/javascript/components/admin/editions/shared/EditionBodyInput/sections/weather/Input.ts, nabeletter/web/app/javascript/components/admin/editions/shared/EditionBodyInput/sections/weather/node.ts, nabeletter/web/app/javascript/i18n/index.ts, nabeletter/web/app/services/delivery_service.rb
fixes:
- delivery bug
- editor analytics
- pixel moved to header
- meetings analytics links
=> [nabeletter] basic ad unit support

nabeletter/web/app/javascript/components/admin/editions/shared/EditionBodyInput/sections/events/node.ts, nabeletter/web/app/javascript/components/admin/editions/shared/EditionBodyInput/sections/meetings/node.ts, nabeletter/web/app/javascript/components/admin/editions/shared/EditionBodyInput/sections/news/node.ts, nabeletter/web/app/javascript/components/admin/subscriptions/list.ts, nabeletter/web/app/resources/subscription_resource.rb, nabeletter/web/config/initializers/jsonapi_resources.rb
- fix zoom link format
- fix events image src
=> [nabeletter] subscriptions: email filter
